# Generated by Django 3.1.5 on 2021-03-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210329_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_kabid',
            field=models.BooleanField(default=False),
        ),
    ]
