# Generated by Django 3.1.5 on 2021-03-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_role_is_kabid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_id',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
