# Generated by Django 3.1.5 on 2021-03-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rencana_kerja', '0002_auto_20210330_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buatrencana',
            name='updated_at',
            field=models.DateTimeField(auto_created=True, default=0),
        ),
    ]
